name: Update All Interviews

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Make PATCH request
      run: |
        curl -X PATCH https://hirewithai-backend.onrender.com/interviews/update